### PR TITLE
LRSD-3986 Fix navigation panel toggle

### PR DESCRIPTION
**Pull request by luisacmn**

### CODE REVIEW

**Comment by ryanschuhler** [comment]
@luisacmn, since this effects the navigation we should be updating only code in the [public sites nav fragment](https://github.com/liferay/liferay-portal/tree/master/workspaces/liferay-learn-workspace/client-extensions/liferay-learn-site-initializer/site-initializer/fragments/group/liferay-learn/fragments/public-sites-navigation), not global.js. Also make sure we dont use generated ids since they will not be reliable, it needs to be something we are certain exists in the fragment. Probably a class or id we added to the code

**Review by ryanschuhler — CHANGES_REQUESTED** [review]
Please see comment and update pull

**Comment by luisacmn** [comment]
@ryanschuhler I've updated the code
thanks !

**Comment by ryanschuhler** [comment]
@luisacmn , after looking into it further, we already have customized and control the dialect-tabs fragment in our code. Is it possible to instead of overriding our functionality adding it to this fragment? https://github.com/liferay/liferay-portal/blob/master/workspaces/liferay-learn-workspace/client-extensions/liferay-learn-site-initializer/site-initializer/fragments/group/liferay-learn/fragments/dialect-tabs/index.js

I am happy to discuss further if you don't think this will work, or is a good idea

**Comment by luisacmn** [comment]
@ryanschuhler sure ! changes done. Could you take a look ?

**Comment by ryanschuhler** [comment]
great work! https://github.com/brianchandotcom/liferay-portal/pull/150361

**Pull request closed without merging**
